codestates-seb/seb40_main_034

- client/src/Routes/AppRouter.jsx
> FEAT: Router 초기 설정

- client/src/Pages/Map/Map.jsx
- client/src/Routes/AppRouter.jsx
AppRouter 경로 routes -> Routes 변경
Router에 연결할 Map 담당이 지금 없어서 임시 Map.jsx 파일만 제가 추가해서 import 했습니다
> Fix: AppRouter 경로 변경

- client/src/App.jsx
- client/src/Pages/Map.jsx
- client/src/Routes/AppRouter.jsx
app.jsx 추가
map.jsx 파일 변경
approuter에 map import 했습니다!
> fix: app.jsx 수정 추가

- client/src/initializer.css
폰트 프리뷰 코드를 작성했습니다. 11/16 프론트엔드 오후 회의에 사용할 예정입니다.
> DESIGN: src/initializer.css에  폰트 프리뷰 코드 작성

- client/src/Pages/Login.jsx
- client/src/Routes/AppRouter.jsx
> Feat:LoginPage

- client/.eslintrc.json
- client/.prettierrc.json
- client/src/Routes/AppRouter.jsx
- client/src/initializer.css
1. 현재 폰트 웨이트는 400, 700만 가져오도록 되어 있습니다. (차후 수정 예정) 또한 body의 기본 line-height를 1.5로 수정했습니다.
2. 린트, 프리티어 세팅 파일을 다시 작성했습니다.
> FEAT: Lint/Prettier 세팅파일 작성, Router Import 수정, Font 고정

- client/.eslintrc.json
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/Routes/AppRouter.jsx
- client/src/initializer.css
> feat: Signup Page 틀 구현

- client/src/Api/MyinfoApi.js
- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/FollowModal/style.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Components/MyPage/MyInfo/style.jsx
- client/src/Components/MyPage/MyList/MyList.jsx
- client/src/Components/MyPage/MyList/style.jsx
- client/src/Pages/Edit.jsx
- client/src/Pages/Mypage.jsx
- client/src/Routes/AppRouter.jsx
Mypage CSS 수정
Following/Follower 모달 CSS 수정
Edit 페이지 추가
fixes #55
> Fix: Mypage CSS 수정

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Components/EditDetail/style.jsx
- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/FollowModal/style.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Components/MyPage/MyInfo/style.jsx
- client/src/Components/MyPage/MyList/MyList.jsx
- client/src/Components/MyPage/MyList/style.jsx
- client/src/Pages/Edit.jsx
- client/src/Pages/Mypage.jsx
- client/src/Routes/AppRouter.jsx
Feat: Edit(유저정보 수정) CSS 구현
fixes #55
> Feat: Edit(유저정보 수정) CSS 구현

- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Components/MyPage/MyInfo/style.jsx
- client/src/Components/MyPage/ShareModal/ShareModal.jsx
- client/src/Components/MyPage/ShareModal/style.jsx
Share 버튼 기능, Share시 모달창 구현
fixes #55
> Feat: Share 버튼 기능 추가

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
Login과SignUp 페이지 버튼 수정 및 인풋창 들여쓰기
> Login과SignUp 페이지 버튼 수정 및 인풋창 들여쓰기

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
이메일,비밀번호 유효성 검사 코드 만들었습니다
(비밀번호 : 8~24자, 1개이상의 문자, 숫자, 특수문자 포함)
> Feat:비밀번호,이메일 유효성 검사

- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
Login 페이지에서 axios를 연결해 json data와 통신을 시도합니다
> test:loginAxiostest

- client/src/Components/EditDetail/style.jsx
- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Components/MyPage/MyInfo/style.jsx
- client/src/Components/MyPage/MyList/style.jsx
- client/src/Components/MyPage/ShareModal/ShareModal.jsx
- client/src/Components/MyPage/ShareModal/style.jsx
Share, Follow 모달창 창외부 클릭시 close되게 수정
Edit 상세페이지 버튼 CSS 수정
fixes #55
> Fix: 모달창 CSS 수정

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/FollowModal/style.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
나를 구독한 사람 (Follower) 목록의  follow/unfollow 버튼 기능 추가
- 내 follow 상태에 따라 follow, unfollow 요청 변경
Fixes #55
> Feat: Follow/Unfollow 기능 추가

- client/src/Components/Common/Btn.jsx
- client/src/Components/Common/Header.jsx
- client/src/Components/Common/InputForm.jsx
- client/src/Components/Common/Sidebar.jsx
- client/src/Components/Common/Tab.jsx
- client/src/Components/Common/Tag.jsx
- client/src/Components/List/List.jsx
- client/src/Pages/Main.jsx
- client/src/Utils/TimeParse.js
1. 헤더의 탭 부분을 추가합니다.
2. 공통 컴포넌트 버튼에 회색 버튼을 추가합니다.
3. 공통 컴포넌트 태그가 (차후) 자동으로 태그 이름에 따른 검색 결과로 이동할 수 있도록 코드 기반을 수정합니다.
4. 공통 컴포넌트에 인풋을 추가합니다.
5. util 폴더에 시간 계산 함수를 추가합니다.
6. 헤더, 사이드바, 메인 페이지, 리스트의 디자인이 약간 변화합니다.
> FEAT: 헤더 탭 추가, 공통 컴포넌트 및 시간 계산 함수 추가

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
Json server를 이용해 axios로 login, signup 구현 중입니다
> Feat: signupAxioswithJsonserver

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/EditDetail.jsx
Edit 회원정보 수정 요청 추가
-profile 이미지 업로드 및 변경, 닉네임 패스워드 변경 요청 추가
-이미지 업로드시 비동기 문제 fix
fixes #55
> Feat: 회원정보 edit 요청 추가

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/DeleteModal/DeleteModal.jsx
- client/src/Components/EditDetail/DeleteModal/style.jsx
- client/src/Components/EditDetail/EditDetail.jsx
Feat: 회원탈퇴 Modal CSS구현
fixes #55
> Feat: 회원탈퇴 Modal CSS구현

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
> Feat:styledComponent위치이동

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/DeleteModal/DeleteModal.jsx
- client/src/Components/EditDetail/EditDetail.jsx
Fix: Edit 오류 수정
-comflict merge시 발생한 오류 수정
> Fix: Edit 오류 수정

- client/src/Api/LoginBtn.js
- client/src/Components/Validation/Emailvalid.jsx
- client/src/Components/Validation/Pwvalid.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/Store/Cookie.js
> Fix:린트설정변경시 생긴 에러 해결

- server/buildspec.yml
> [FEAT] buildspec.yml 파일 수정

- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Components/EditDetail/style.jsx
Fix: Edit페이지 버튼, Input CSS 수정
fixes #55
> Fix: Edit 버튼 CSS 수정

- client/src/Components/MyPage/MyInfo/style.jsx
> Fix/grid 화면 fix

- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/FollowModal/style.jsx
- client/src/Components/MyPage/MyInfo/style.jsx
- client/src/Components/MyPage/MyList/MyList.jsx
- client/src/Components/MyPage/ShareModal/ShareModal.jsx
- client/src/Components/MyPage/ShareModal/style.jsx
> Fix: Mypage Grid 수정

- client/src/Components/MapSide/MapSide.jsx
- client/src/Components/MapSide/style.jsx
- client/src/Components/MapView/MapView.jsx
- client/src/Pages/Map.jsx
Feat:Map CSS component 추가
-Mapview , Review 창 component 추가
fixed #118
> Feat:Map CSS component 추가

- client/src/Api/DetailApi.js
- client/src/Components/Detail/CommentList.jsx
> link to 추가

- client/package-lock.json
- client/package.json
- client/public/index.html
- client/src/Api/Valid.js
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/storage/Cookie.js
닉네임 유효성 검사를 추가했습니다 (소문자 + 숫자 / 8~15자)
닉네임, 이메일, 비밀번호 유효성검사 함수를 api폴더 내에 js파일로 만들었습니다
로그인, 회원가입 화면 높이를 조절했습니다
> Feat:유효성검사함수파일추가

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/Routes/AppRouter.jsx
- client/src/storage/Cookie.js
회원가입/로그인이 가능합니다 
제대로 작동하면 로그인 시 메인페이지로 이동합니다.
현재 회원가입 시 응답이 201 또는 200으로 와서 그건 찾아봐야 할거 같네요
> Feat:회원가입기능/로그인시쿠키세팅

- client/src/Components/Common/FollowList.jsx
- client/src/Pages/Post.jsx
- client/src/Routes/AppRouter.jsx
1. post 페이지를 추가합니다.
2. 라우터에 post를 추가합니다.
> Feat: POST 페이지 추가 및 버튼 연결, 라우터 수정

- client/src/Components/Common/WriteBtn.jsx
> FEAT: 글쓰기 버튼과 컴포넌트 연결

- client/src/Pages/Logout.jsx
- client/src/Store/Auth.js
> feat/redux-persist 수정

- client/src/Pages/Loading.jsx
> feat/Loading 컴포넌트

- client/src/Pages/Login.jsx
- client/src/Pages/Logout.jsx
- client/src/Pages/Signup.jsx
- client/src/Store/Auth.js
> Fix:Redux auth 파일 수정

- client/package.json
- client/src/Api/root.js
> FIX: API ROOT 실제 서버 주소로 수정

- client/src/Api/LoginApi.js
- client/src/Components/Detail/DetailModal.jsx
- client/src/Pages/Detail.jsx
- client/src/Pages/Loading.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
> Fix:회원가입/로그인누를시에러메세지보이게수정

- client/src/Pages/Footer.jsx
- client/src/Pages/Login.jsx
Footer code는 추가 했지만 컴포넌트에 추가하지는 않아서 표시되는 화면은 없습니다.
setCookie코드는 일단 accessToken용 코드만 남겨두었습니다.
> Feat:loginSetcookie코드수정

- client/src/Api/nicknameCheck.js
- client/src/App.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/Store/Auth.js
로그아웃버튼을 임시로 만들었습니다. 이후 햄버거 메뉴로 버튼은 이동할 계획입니다.
로그인 후 로그인 화면 하단에 로그아웃 버튼을 누르면 persistStore내의 state가 초기화 됩니다.
+ 로그인, 회원가입 창의 로고를 변경했습니다.
> Feat:로그아웃기능추가

- server/src/main/java/com/example/seb_main_project/member/controller/MemberController.java
- server/src/main/java/com/example/seb_main_project/member/dto/AuthDto.java
- server/src/main/java/com/example/seb_main_project/member/mapper/MemberMapper.java
- server/src/main/java/com/example/seb_main_project/member/service/DBMemberService.java
- server/src/main/java/com/example/seb_main_project/member/service/MemberService.java
- server/src/main/java/com/example/seb_main_project/postlike/controller/PostLikeController.java
> [FEAT] 프로필 수정, 임시로 닉네임만 수정 가능하게 설정

- client/src/Api/nicknameCheck.js
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
Feat:닉네임중복확인 기능을 추가했습니다.
버튼의 모양과 추가적인 기능은 이후 수정하겠습니다. :)
> Feat:닉네임중복확인 기능을 추가했습니다

- client/src/Api/MainApi.js
- client/src/Components/Common/Tab.jsx
- client/src/Components/List/List.jsx
- client/src/Components/Main/ListContainer.jsx
- client/src/Components/Post/Tagform.jsx
- client/src/Hooks/useInput.js
- client/src/Hooks/useTag.js
- client/src/Pages/Main.jsx
- client/src/Pages/Post.jsx
1. 무한스크롤을 메인 페이지에 구현합니다.
2. 글 작성 페이지에서 태그 폼이 작동하도록 수정합니다.
> FEAT: 무한스크롤 구현 및 글 작성 페이지 추가

- client/src/Pages/Login.jsx
- client/src/Pages/Logout.jsx
- client/src/Pages/Signup.jsx
닉네임 중복 확인 버튼을 수정했습니다
로그인 하고 sign out을 누르면 연결되는 로그아웃 페이지를 만들었습니다.
로그아웃을 누르면 store내의 state와 쿠키가 초기화 됩니다.
> Feat:닉네임중복확인버튼 수정/ 로그아웃페이지 생성

- client/src/Components/Common/Btn.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
비밀번호 보이기 버튼 색을 수정했습니다.
에러 메세지 위치를 수정했습니다.
> Style:로그인/회원가입화면수정

- client/src/Api/MapApi.js
- client/src/Components/MapPagination/MapPagination.jsx
- client/src/Components/MapPagination/style.jsx
- client/src/Components/MapSide/MapSide.jsx
- client/src/Components/MapSide/style.jsx
- client/src/Components/MapView/MapView.jsx
- client/src/Pages/Map.jsx
Feat: Map Pagination front side 추가
> Feat: Map Pagination front side 추가

- client/src/Routes/AppRouter.jsx
이제 메인 페이지에서 글 상세 페이지로 이동이 가능합니다.
> FIX: 라우터 경로에 있던 오탈자를 수정합니다.

- client/package-lock.json
- client/package.json
- client/src/Components/Common/Btn.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Post.jsx
- client/src/Utils/customAlert.js
- client/src/initializer.css
SweetAlert를 적용합니다.
사용법: Utils/customAlert에서 customAlert import 후, customAlert('알림 문구') 호출
> FEAT: Custon Alert 적용

- .github/workflows/fe_deploy.yml
카카오 키가 환경변수에 생성되지 않던 문제를 수정합니다.
> FIX: 배포 자동화가 제대로 진행되지 않는 문제 수정

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
- client/src/Utils/customAlert.js
회원가입페이지의 alert창을 customAlert로 대체했습니다
> Style:SignupAlertEdit

- .github/workflows/fe_deploy.yml
> FIX: 배포 자동화 yml의 오탈자를 수정합니다.

- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
input창을 벗어낫을때 유효성검사 결과에 따라 에러메세지를 보여주는 onBlur 이벤트를 추가했습니다
> Feat:onBlurEvent

- client/src/Api/PostApi.js
- client/src/Components/Post/PlaceSearchModal.jsx
- client/src/Pages/LayoutHS.jsx
- client/src/Pages/Main.jsx
- client/src/Pages/Post.jsx
또, 로그인이 되어야 글 작성 버튼이 보이도록 수정합니다.
> FEAT: 글쓰기 페이지에 장소 검색 기능이 추가됩니다.

- server/src/main/java/com/example/seb_main_project/member/dto/AuthDto.java
- server/src/main/java/com/example/seb_main_project/security/controller/SecurityController.java
- server/src/main/java/com/example/seb_main_project/security/filter/JwtAuthenticationFilter.java
- server/src/main/java/com/example/seb_main_project/security/filter/JwtVerificationFilter.java
- server/src/main/java/com/example/seb_main_project/security/jwt/JwtTokenizer.java
- server/src/main/java/com/example/seb_main_project/security/repository/RefreshTokenRepository.java
- server/src/main/java/com/example/seb_main_project/security/service/AuthService.java
해당 헤더를 클라이언트에 반환한 뒤, 이를 리퀘스트 요청에 Authorization 헤더에 포함된 요청을 받아 memberId 추출
> [FIX] Authorization response header 리턴

- client/src/Components/Common/InputForm.jsx
- client/src/Components/Common/MiniProfile.jsx
- client/src/Components/Layout/Header.jsx
- client/src/Components/Layout/Sidebar.jsx
- client/src/Components/Layout/Tab.jsx
- client/src/Components/Main/List.jsx
- client/src/Pages/LayoutHS.jsx
- client/src/Pages/Post.jsx
- client/src/Routes/AppRouter.jsx
> FEAT: 로그인된 유저 정보를 STORE에서 일부 가져오도록 변경

- client/src/Pages/Login.jsx
- client/src/Store/Auth.js
- client/src/Store/Headerauth.js
- client/src/Store/index.js
로그인 상태로 로그인 페이지에 접근 시 메인화면으로 가는 useEffect를 추가했습니다.
로그인 시 store에 accessToken과 refreshToken에 넣도록 코드 추가 했습니다.
> Feat:로그인페이지에useEffect추가

- client/src/Components/Detail/DetailModal.jsx
- client/src/Pages/Detail.jsx
> feat/ main_detail 통신

- client/src/Api/DetailApi.js
- client/src/Components/Detail/CommentList.jsx
> feat/댓글 삭제 ver1

- client/src/Pages/Detail.jsx
> feat/mac 2번 클릭 방지

- client/src/Components/MyPage/MyInfo/MyInfo.jsx
> Fix: Edit navi 경로수정

- client/src/Pages/Signup.jsx
로그인 상태에서 회원가입 페이지 접근시 메인 화면으로 이동하도록 useEffect를 추가했습니다.
> Feat:SignupPageRedirection

- client/src/Api/MyinfoApi.js
- client/src/Components/EditDetail/EditDetail.jsx
> Fix: Mypage Edit api 요청 수정

- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Signup.jsx
> Feat닉네임수정시중복확인버튼추가

- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Pages/Signup.jsx
> Feat:회원가입서버변경

- client/src/Components/EditDetail/EditDetail.jsx
> Feat:Edit페이지Alert변경

- client/src/Api/DetailApi.js
- client/src/Pages/Detail.jsx
> feat/게시글 삭제

- client/src/Api/DetailApi.js
- client/src/Pages/Detail.jsx
- client/src/Utils/deleteAlert.js
> feat/삭제 확인

- client/src/Components/Layout/AboutBtn.jsx
- client/src/Components/Layout/WriteBtn.jsx
Feat:writeBtn과 AboutBtn의 위치를 변경했습니다
> Feat:writeBtn위치변경

- client/src/Api/HeaderApi.js
- client/src/Components/Common/Tag.jsx
- client/src/Components/Main/List.jsx
- client/src/Components/Main/ListContainer.jsx
- client/src/Components/Post/Tagform.jsx
- client/src/Pages/Post.jsx
> FIX: 메인 화면과 글 작성 시 이미지가 정상적으로 표시됩니다

- client/src/Pages/Map.jsx
상세페이지 진입시 글의 위치를 클릭하면 해당 위치의 지도를 마커와 함께 보여줍니다.
> Feat:글상세페이지 수정

- client/src/Components/Main/ListContainer.jsx
- client/src/Pages/Loading.jsx
로딩페이지를 수정했습니다 
메인페이지의 데이터가 렌더링 완료되기 전에 로딩페이지가 나옵니다
> Feat:LoadingPageEdit

- client/src/Components/Layout/Tab.jsx
탭에 있는 맵버튼 클릭시 서울역을 마커로 지도를 보여줍니다.
> Feat:기본맵주소변경

- client/src/Api/MapApi.js
- client/src/Components/MapSide/MapSide.jsx
> Feat:Mapside

- client/src/Components/EditDetail/EditDetail.jsx
- client/src/Components/Main/ListContainer.jsx
- client/src/Components/MapPagination/MapPagination.jsx
- client/src/Components/MapSide/MapSide.jsx
- client/src/Components/MyPage/FollowModal/FollowModal.jsx
- client/src/Components/MyPage/MyInfo/MyInfo.jsx
- client/src/Pages/Detail.jsx
- client/src/Pages/Login.jsx
- client/src/Pages/Post.jsx
- client/src/Pages/Signup.jsx
detailApi제외 나머지 파일들에서 console.log제거 했습니다.
> console창 제거 
